# MPD configuration file (standalone)
# Version 3.0
# example file: doc/mpdconf.example in the build directory
# Documentation: http://mpd.readthedocs.io/latest/user.html

### Files and directories
music_directory		"/media/music"
playlist_directory	"/var/lib/mpd/playlists"
state_file			"/var/lib/mpd/state"
pid_file			"/var/run/mpd/pid"
log_file			"/var/log/mpd/mpd.log"

### General music daemon options
user				"mpd"
auto_update			"yes"
auto_update_depth	"3"

### Symbolic link behavior
follow_outside_symlinks	"no"

### Database
database {
	plugin			"simple"
	path			"/var/lib/mpd/db"
	cache_directory	"/var/lib/mpd/cache"
}

### Audio Output
audio_output {
	type		"alsa"
	name		"USB0"
	device		"hw:0,0"
	dop			"yes"
	priority	"FIFO:1"
}

### Plugin configuration

#resampler {
#	plugin	"soxr"
#	quality	"very high"
#}

#playlist_plugin {
#	name			"cue"
#	enabled			"true"
#	as_directory	"yes"
#}

### Internal buffer
input_cache {
	size	"512 MB"
}

### Jan's real time patch
realtime_option {
	memlock				"yes"
	stack_reserve		"1024"
	heap_reserve		"0"
    
	io_priority			"OTHER:0"
	rtio_priority		"FIFO:2"
	main_priority		"OTHER:0"
	player_priority		"FIFO:1"
	decoder_priority	"FIFO:2"
	update_priority		"OTHER:0"
}
