#!/bin/sh
#
# wpa_supplicant	Starts wireless connection handler.
#

DAEMON=wpa_supplicant
PIDFILE="/var/run/$DAEMON.pid"
bin_file=/usr/sbin/wpa_supplicant
cfg_file="/etc/wpa_supplicant/wpa_supplicant.conf"
log_file="/var/log/wpa_supplicant.log"

# Assure that at least one interface exists. 
[ -e /sys/class/net/wlan0 ] || exit 0

# allow for multiple interfaces
config=""
for i in /sys/class/net/wlan?; do
	if [ -n "${config}" ]; then config="${config} -N"; fi
	config="${config} -i`basename $i` -Dnl80211,wext -c${cfg_file}"
done

start() {
	echo -n "Starting $DAEMON... "
	start-stop-daemon -S -b -m -p $PIDFILE -x /usr/sbin/wpa_supplicant -- -B -f${log_file} ${config}
	[ ! -z $(pidof $DAEMON) ] && echo "OK" || echo "FAIL"
}

stop() {
	echo -n "Stopping $DAEMON... "
	start-stop-daemon -K -p $PIDFILE
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

restart() {
	stop
	start
}

case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
