#!/bin/sh
#
# sshd        Starts sshd.
#

SSH_DIR="/etc/ssh"

# protocol 1 has been removed
SSH_KEY_FILES="ssh_host_dsa_key \
	ssh_host_ecdsa_key \
	ssh_host_ed25519_key \
	ssh_host_rsa_key"

SSH_SERVER_DIR="$SSH_DIR"
SSH_USER_DIR="/root/.ssh"
PUBLIC_FILES="moduli ssh*_config *.pub"

# Make sure the ssh-keygen program exists
[ -f /usr/bin/ssh-keygen ] || exit 0

# Make sure the SSH directory exists
mkdir -p $SSH_DIR

# key file permissions were lost during restore from FAT file system
restore_key_permissions() {
	ssh_dir="$1"
	# first set all files to acessible by user only
	ssh_pattern="$ssh_dir/*"
	# if pattern can be expanded, files exist
	[ ! "$ssh_pattern" = "$(echo $ssh_pattern)" ] && chmod 600 $ssh_pattern
	# now add read permisson for public files
	for ssh_file in $PUBLIC_FILES; do
		ssh_pattern="$ssh_dir/$ssh_file"
		[ ! "$ssh_pattern" = "$(echo $ssh_pattern)" ] && chmod a+r $ssh_pattern
	done
}

# generate any missing keys
generate_missing_keys() {
	echo -n "Generating missing SSH keys "
	for key_file in $SSH_KEY_FILES; do
		if [ ! -f $SSH_DIR/$key_file ] ; then
			key_type=${key_file##ssh_host_}
			key_type=${key_type%%_key}
			echo -n "$key_type "
			/usr/bin/ssh-keygen -t $key_type -f $SSH_DIR/$key_file -C '' -N '' > /dev/null 2>&1
		fi
	done
	echo "[OK]"
}

umask 022

start() {
	restore_key_permissions "$SSH_SERVER_DIR"
	restore_key_permissions "$SSH_USER_DIR"
	generate_missing_keys
	echo -n "Starting sshd: "
	/usr/sbin/sshd -E /var/log/sshd.log
	touch /var/lock/sshd
	echo "OK"
}

stop() {
	echo -n "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
