#!/bin/sh
#
# localopt	Run optimization scripts local to the machine. 
#			This may include removal of unused hardware drivers.
#
# shellcheck disable=SC1091	# do not follow include files

### this is a startup only script
[ "$1" != "start" ] && exit 0

### functions that are used in more than one init script
[ -x /etc/init.d/init_functions ] && . /etc/init.d/init_functions

### initialize system variables
[ -f /etc/nabla.conf ] && . /etc/nabla.conf

### check if feature is enabled
[ "$NABLA_LOCAL_OPTIMIZATION" != "Y" ] && exit 0

printf "Run local optimizations: "
mount_directory=/media
# shellcheck disable=SC2154	# ignore config_directory from included file
home_overlay=${mount_directory}/${NABLA_PARTITION}/${config_directory}/root
if [ -d "$home_overlay" ]; then
	# shellcheck source=/dev/null
	for s in "$home_overlay"/*.sh;  do
		. "$s"
	done
fi
echo "Done"
