#!/bin/sh
#
# rtopt	Optimize RT priorities for audio related processes.
#

### initialize system variables
[ -x /etc/nabla.conf ] && . /etc/nabla.conf

### functions that are used in more than one init script
[ -x /etc/init.d/init_functions ] && . /etc/init.d/init_functions

### do not run during shutdown
if [ "$1" = "stop" ];  then
	exit 0;
fi

# Change CPU frequency scaling governor to performance
governor="performance"
available_cpus="/sys/devices/system/cpu/cpu[0-9]*"
for cpu in $available_cpus; do
	interface=$cpu/cpufreq
	if $([ -d $interface ] && grep -q $governor $interface/scaling_available_governors); then
		echo $governor > $interface/scaling_governor
	fi
done

# processes that should run with low real-time priority
for process in $LOWER_PRIORITY_LIST; do
	for pid in $(_get_pid $process); do chrt $(_chrt_policy) -p $LO_PRIO $pid; done
done
# processes that should run with medium real-time priority
for process in $HIGHER_PRIORITY_LIST; do
	for pid in $(_get_pid $process); do chrt $(_chrt_policy) -p $HI_PRIO $pid; done
done
# processes that should run with high real-time priority
for process in $REALTIME_PRIORITY_LIST; do
	for pid in $(_get_pid $process); do chrt $(_chrt_policy) -p $RT_PRIO $pid; done
done

# favor discarding mapped (file cache) over unmapped (process memory) pages
echo 10 > /proc/sys/vm/swappiness

# disable real-time throttling
# OS Jitter text recommends disabling completely (sched_rt_runtime_us == -1)
# linuxrealtime.org/index.php/Improving_the_Real-Time_Properties proposes 1000000 
# rtt default levels are (0.95s /1.00s)
echo "1000000" > /proc/sys/kernel/sched_rt_runtime_us # rt share of period
echo "1000000" > /proc/sys/kernel/sched_rt_period_us # accounting period

# Delay vm statistics timer.  This may be obsolete since Christoph Lameter's 
# vm shepherd patch.  For reference see lkml.org/lkml/2013/9/4/379
vm_statistics=/proc/sys/vm/stat_interval
[ -f $vm_statistics ] && echo 300 > $vm_statistics

# change block device writeback affinity
echo 0 > /sys/bus/workqueue/devices/writeback/numa
echo $(_get_nrt_cpumask) > /sys/bus/workqueue/devices/writeback/cpumask

# change timer frequency, this patch originated from 
# https://linuxmusicians.com/viewtopic.php?t=15378
echo 2048 > /sys/class/rtc/rtc0/max_user_freq
echo 2048 > /proc/sys/dev/hpet/max-user-freq

# set processor affinity to partitioned cpu
rt_id=$(_get_rt_cpuid)
for process in $CPU_AFFINITY_LIST; do
	for pid in $(_get_pid $process); do
		taskset -p $(_get_cpumask $rt_id) $pid
	done
done
