#!/bin/sh
#
# led	Activates LEDs on ALIX platform.
#

sysfs=/sys/class/leds

# shellcheck source=/dev/null
[ -x /etc/init.d/init_functions ] && . /etc/init.d/init_functions

# sysfs entries for LEDs will become obsolete with Linux 6.17
[ ! -d "$sysfs" ] || _is_empty "$sysfs" && exit 0

start() {
	n=1
	for l in $(printf '%s\0' "$sysfs"/* | sort -V); do
		if [ "$n" -eq 1 ]; then
			echo heartbeat > "$l"/trigger
		elif [ "$n" -eq 2 ]; then
			echo netdev > "$l"/trigger
			echo eth0 > "$l"/device_name
			echo 1 > "$l"/tx
		elif [ "$n" -eq 3 ]; then
			echo timer > "$l"/trigger
			echo 500  > "$l"/delay_on
			echo 1500  > "$l"/delay_off
		else
			printf "Unexpected sysfs entry: %s" "$l"
		fi
		n=$((n+1))
	done
}

stop() {
	for l in $(printf '%s\0' "$sysfs"/* | sort -rV); do
		echo none > $l/trigger
	done
}

load_module() {
	grep -q "^$1" /proc/modules || modprobe "$1"
}

load_module ledtrig_heartbeat
load_module ledtrig_netdev
load_module ledtrig_timer

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
