#!/bin/sh
#
# led	Modifies LEDs on Raspberry Pi platform.
#

sysfs=/sys/class/leds

# shellcheck source=/dev/null
[ -x /etc/init.d/init_functions ] && . /etc/init.d/init_functions

# sysfs entries for LEDs will become obsolete with Linux 6.17
[ ! -d $sysfs ] || _is_empty "$sysfs" && exit 0

# ACT is the green LED
# PWR is the red LED
# brightness control handles on/off

start() {
	# activity LED initially has heartbeat pattern, so leave it alone
	# echo heartbeat > $sysfs/ACT/trigger
	echo timer > $sysfs/PWR/trigger
	echo 500  > $sysfs/PWR/delay_on
	echo 1500  > $sysfs/PWR/delay_off
}

stop() {
	echo 0 > $sysfs/ACT/brightness
	echo 0 > $sysfs/PWR/brightness
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
